return {
	['enable_Jokers'] = true,
	['enable_Stands'] = true,
	['enable_Consumables'] = true,
	['enable_Decks'] = true,
	['enable_Tags'] = true,
	['enable_Blinds'] = true,
	['enable_BlindReskins'] = true,
	['enable_Challenges'] = true,
	['enable_AltArt'] = false,
	['enable_InsaneStaticSeed'] = false,
	['enable_Queer'] = true,
	['enable_VanillaTweaks'] = true,
	['enable_TarotSkins'] = true,
	['enable_Title'] = true,
}