return {
	['resetTrophies'] = nil,
	['enable_Jokers'] = true,
	['enable_Stands'] = true,
	['enable_Consumables'] = true,
	['enable_Decks'] = true,
	['enable_Tags'] = true,
	['enable_Blinds'] = true,
	['enable_BlindReskins'] = true,
	['enable_Challenges'] = true,
	['enable_Achievements'] = false,
	['enable_AltArt'] = false,
	['enable_SkepticStaticSeed'] = false,
	['enable_Queer'] = true,
	['enable_VanillaTweaks'] = true,
	['enable_TarotSkins'] = true,
}